//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Protocol/Mail.proto
// Note: requires additional types generated from: Protocol/Reward.proto
namespace PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HSMail")]
  public partial class HSMail : global::ProtoBuf.IExtensible
  {
    public HSMail() {}
    
    private int _mailId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailId
    {
      get { return _mailId; }
      set { _mailId = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _sendTimeStamp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"sendTimeStamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sendTimeStamp
    {
      get { return _sendTimeStamp; }
      set { _sendTimeStamp = value; }
    }
    private int _senderId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"senderId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int senderId
    {
      get { return _senderId; }
      set { _senderId = value; }
    }
    private string _senderName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"senderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string senderName
    {
      get { return _senderName; }
      set { _senderName = value; }
    }
    private string _subject;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"subject", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string subject
    {
      get { return _subject; }
      set { _subject = value; }
    }
    private string _content;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private readonly global::System.Collections.Generic.List<RewardItem> _reward = new global::System.Collections.Generic.List<RewardItem>();
    [global::ProtoBuf.ProtoMember(8, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RewardItem> reward
    {
      get { return _reward; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HSMailInfoSync")]
  public partial class HSMailInfoSync : global::ProtoBuf.IExtensible
  {
    public HSMailInfoSync() {}
    
    private readonly global::System.Collections.Generic.List<HSMail> _mailInfo = new global::System.Collections.Generic.List<HSMail>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mailInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HSMail> mailInfo
    {
      get { return _mailInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HSMailRead")]
  public partial class HSMailRead : global::ProtoBuf.IExtensible
  {
    public HSMailRead() {}
    
    private int _mailId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailId
    {
      get { return _mailId; }
      set { _mailId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HSMailReceive")]
  public partial class HSMailReceive : global::ProtoBuf.IExtensible
  {
    public HSMailReceive() {}
    
    private int _mailId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailId
    {
      get { return _mailId; }
      set { _mailId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HSMailReceiveRet")]
  public partial class HSMailReceiveRet : global::ProtoBuf.IExtensible
  {
    public HSMailReceiveRet() {}
    
    private int _mailId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailId
    {
      get { return _mailId; }
      set { _mailId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HSMailReceiveAll")]
  public partial class HSMailReceiveAll : global::ProtoBuf.IExtensible
  {
    public HSMailReceiveAll() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HSMailReceiveAllRet")]
  public partial class HSMailReceiveAllRet : global::ProtoBuf.IExtensible
  {
    public HSMailReceiveAllRet() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _receiveMailId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"receiveMailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> receiveMailId
    {
      get { return _receiveMailId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HSMailNew")]
  public partial class HSMailNew : global::ProtoBuf.IExtensible
  {
    public HSMailNew() {}
    
    private HSMail _mail;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public HSMail mail
    {
      get { return _mail; }
      set { _mail = value; }
    }
    private int _overflowMailId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"overflowMailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int overflowMailId
    {
      get { return _overflowMailId; }
      set { _overflowMailId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HSMailDelete")]
  public partial class HSMailDelete : global::ProtoBuf.IExtensible
  {
    public HSMailDelete() {}
    
    private int _mailId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailId
    {
      get { return _mailId; }
      set { _mailId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HSMailDeleteRet")]
  public partial class HSMailDeleteRet : global::ProtoBuf.IExtensible
  {
    public HSMailDeleteRet() {}
    
    private int _mailId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailId
    {
      get { return _mailId; }
      set { _mailId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}