// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Const.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Const.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* chatType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* kickReason_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Const_2eproto() {
  protobuf_AddDesc_Const_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Const.proto");
  GOOGLE_CHECK(file != NULL);
  chatType_descriptor_ = file->enum_type(0);
  kickReason_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Const_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_Const_2eproto() {
}

void protobuf_AddDesc_Const_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013Const.proto*C\n\010chatType\022\016\n\nCHAT_WORLD\020"
    "\001\022\022\n\016CHAT_BROADCAST\020\002\022\023\n\017WORLD_BROADCAST"
    "\020\003*n\n\nkickReason\022\023\n\017DUPLICATE_LOGIN\020\001\022\023\n"
    "\017SERVER_SHUTDOWN\020\002\022\022\n\016LOGIN_FORBIDEN\020\003\022\016"
    "\n\nKICKED_OUT\020\004\022\022\n\016SERVER_RESTART\020\005B\030\n\026co"
    "m.hawk.game.protocol", 220);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Const.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Const_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Const_2eproto {
  StaticDescriptorInitializer_Const_2eproto() {
    protobuf_AddDesc_Const_2eproto();
  }
} static_descriptor_initializer_Const_2eproto_;
const ::google::protobuf::EnumDescriptor* chatType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return chatType_descriptor_;
}
bool chatType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* kickReason_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return kickReason_descriptor_;
}
bool kickReason_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
