// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol/Consume.proto

package com.hawk.game.protocol;

public final class Consume {
  private Consume() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConsumeItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 type = 1;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 类型
     * </pre>
     */
    int getType();

    // optional int64 id = 2;
    /**
     * <code>optional int64 id = 2;</code>
     *
     * <pre>
     * 唯一Id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 2;</code>
     *
     * <pre>
     * 唯一Id
     * </pre>
     */
    long getId();

    // required string itemId = 3;
    /**
     * <code>required string itemId = 3;</code>
     *
     * <pre>
     * 物品编号
     * </pre>
     */
    boolean hasItemId();
    /**
     * <code>required string itemId = 3;</code>
     *
     * <pre>
     * 物品编号
     * </pre>
     */
    java.lang.String getItemId();
    /**
     * <code>required string itemId = 3;</code>
     *
     * <pre>
     * 物品编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getItemIdBytes();

    // optional int64 count = 4;
    /**
     * <code>optional int64 count = 4;</code>
     *
     * <pre>
     * 实体对象直接移除对象
     * </pre>
     */
    boolean hasCount();
    /**
     * <code>optional int64 count = 4;</code>
     *
     * <pre>
     * 实体对象直接移除对象
     * </pre>
     */
    long getCount();
  }
  /**
   * Protobuf type {@code ConsumeItem}
   *
   * <pre>
   * ------------------------------------------------------- struct -------------------------------------------------------
   * 推送道具 装备 角色的需要移除的Id的列表
   * </pre>
   */
  public static final class ConsumeItem extends
      com.google.protobuf.GeneratedMessage
      implements ConsumeItemOrBuilder {
    // Use ConsumeItem.newBuilder() to construct.
    private ConsumeItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConsumeItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConsumeItem defaultInstance;
    public static ConsumeItem getDefaultInstance() {
      return defaultInstance;
    }

    public ConsumeItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConsumeItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              itemId_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              count_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.Consume.internal_static_ConsumeItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.Consume.internal_static_ConsumeItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.Consume.ConsumeItem.class, com.hawk.game.protocol.Consume.ConsumeItem.Builder.class);
    }

    public static com.google.protobuf.Parser<ConsumeItem> PARSER =
        new com.google.protobuf.AbstractParser<ConsumeItem>() {
      public ConsumeItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConsumeItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ConsumeItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 类型
     * </pre>
     */
    public int getType() {
      return type_;
    }

    // optional int64 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <code>optional int64 id = 2;</code>
     *
     * <pre>
     * 唯一Id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 id = 2;</code>
     *
     * <pre>
     * 唯一Id
     * </pre>
     */
    public long getId() {
      return id_;
    }

    // required string itemId = 3;
    public static final int ITEMID_FIELD_NUMBER = 3;
    private java.lang.Object itemId_;
    /**
     * <code>required string itemId = 3;</code>
     *
     * <pre>
     * 物品编号
     * </pre>
     */
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string itemId = 3;</code>
     *
     * <pre>
     * 物品编号
     * </pre>
     */
    public java.lang.String getItemId() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          itemId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string itemId = 3;</code>
     *
     * <pre>
     * 物品编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getItemIdBytes() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 count = 4;
    public static final int COUNT_FIELD_NUMBER = 4;
    private long count_;
    /**
     * <code>optional int64 count = 4;</code>
     *
     * <pre>
     * 实体对象直接移除对象
     * </pre>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 count = 4;</code>
     *
     * <pre>
     * 实体对象直接移除对象
     * </pre>
     */
    public long getCount() {
      return count_;
    }

    private void initFields() {
      type_ = 0;
      id_ = 0L;
      itemId_ = "";
      count_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasItemId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getItemIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getItemIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.Consume.ConsumeItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Consume.ConsumeItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Consume.ConsumeItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Consume.ConsumeItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Consume.ConsumeItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Consume.ConsumeItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Consume.ConsumeItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.Consume.ConsumeItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Consume.ConsumeItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Consume.ConsumeItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.Consume.ConsumeItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConsumeItem}
     *
     * <pre>
     * ------------------------------------------------------- struct -------------------------------------------------------
     * 推送道具 装备 角色的需要移除的Id的列表
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.Consume.ConsumeItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.Consume.internal_static_ConsumeItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.Consume.internal_static_ConsumeItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.Consume.ConsumeItem.class, com.hawk.game.protocol.Consume.ConsumeItem.Builder.class);
      }

      // Construct using com.hawk.game.protocol.Consume.ConsumeItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        itemId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        count_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.Consume.internal_static_ConsumeItem_descriptor;
      }

      public com.hawk.game.protocol.Consume.ConsumeItem getDefaultInstanceForType() {
        return com.hawk.game.protocol.Consume.ConsumeItem.getDefaultInstance();
      }

      public com.hawk.game.protocol.Consume.ConsumeItem build() {
        com.hawk.game.protocol.Consume.ConsumeItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.Consume.ConsumeItem buildPartial() {
        com.hawk.game.protocol.Consume.ConsumeItem result = new com.hawk.game.protocol.Consume.ConsumeItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.itemId_ = itemId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.Consume.ConsumeItem) {
          return mergeFrom((com.hawk.game.protocol.Consume.ConsumeItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.Consume.ConsumeItem other) {
        if (other == com.hawk.game.protocol.Consume.ConsumeItem.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasItemId()) {
          bitField0_ |= 0x00000004;
          itemId_ = other.itemId_;
          onChanged();
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasItemId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.Consume.ConsumeItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.Consume.ConsumeItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 type = 1;
      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 类型
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 类型
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional int64 id = 2;
      private long id_ ;
      /**
       * <code>optional int64 id = 2;</code>
       *
       * <pre>
       * 唯一Id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 id = 2;</code>
       *
       * <pre>
       * 唯一Id
       * </pre>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 2;</code>
       *
       * <pre>
       * 唯一Id
       * </pre>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 2;</code>
       *
       * <pre>
       * 唯一Id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }

      // required string itemId = 3;
      private java.lang.Object itemId_ = "";
      /**
       * <code>required string itemId = 3;</code>
       *
       * <pre>
       * 物品编号
       * </pre>
       */
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string itemId = 3;</code>
       *
       * <pre>
       * 物品编号
       * </pre>
       */
      public java.lang.String getItemId() {
        java.lang.Object ref = itemId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          itemId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string itemId = 3;</code>
       *
       * <pre>
       * 物品编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getItemIdBytes() {
        java.lang.Object ref = itemId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string itemId = 3;</code>
       *
       * <pre>
       * 物品编号
       * </pre>
       */
      public Builder setItemId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string itemId = 3;</code>
       *
       * <pre>
       * 物品编号
       * </pre>
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        itemId_ = getDefaultInstance().getItemId();
        onChanged();
        return this;
      }
      /**
       * <code>required string itemId = 3;</code>
       *
       * <pre>
       * 物品编号
       * </pre>
       */
      public Builder setItemIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        itemId_ = value;
        onChanged();
        return this;
      }

      // optional int64 count = 4;
      private long count_ ;
      /**
       * <code>optional int64 count = 4;</code>
       *
       * <pre>
       * 实体对象直接移除对象
       * </pre>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 count = 4;</code>
       *
       * <pre>
       * 实体对象直接移除对象
       * </pre>
       */
      public long getCount() {
        return count_;
      }
      /**
       * <code>optional int64 count = 4;</code>
       *
       * <pre>
       * 实体对象直接移除对象
       * </pre>
       */
      public Builder setCount(long value) {
        bitField0_ |= 0x00000008;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 count = 4;</code>
       *
       * <pre>
       * 实体对象直接移除对象
       * </pre>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        count_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ConsumeItem)
    }

    static {
      defaultInstance = new ConsumeItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ConsumeItem)
  }

  public interface HSConsumeInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .SynPlayerAttr playerAttr = 1;
    /**
     * <code>optional .SynPlayerAttr playerAttr = 1;</code>
     *
     * <pre>
     * 玩家同步信息
     * </pre>
     */
    boolean hasPlayerAttr();
    /**
     * <code>optional .SynPlayerAttr playerAttr = 1;</code>
     *
     * <pre>
     * 玩家同步信息
     * </pre>
     */
    com.hawk.game.protocol.Player.SynPlayerAttr getPlayerAttr();
    /**
     * <code>optional .SynPlayerAttr playerAttr = 1;</code>
     *
     * <pre>
     * 玩家同步信息
     * </pre>
     */
    com.hawk.game.protocol.Player.SynPlayerAttrOrBuilder getPlayerAttrOrBuilder();

    // repeated .SynMonsterAttr monstersAttr = 2;
    /**
     * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
     *
     * <pre>
     * 宠物同步信息
     * </pre>
     */
    java.util.List<com.hawk.game.protocol.Monster.SynMonsterAttr> 
        getMonstersAttrList();
    /**
     * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
     *
     * <pre>
     * 宠物同步信息
     * </pre>
     */
    com.hawk.game.protocol.Monster.SynMonsterAttr getMonstersAttr(int index);
    /**
     * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
     *
     * <pre>
     * 宠物同步信息
     * </pre>
     */
    int getMonstersAttrCount();
    /**
     * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
     *
     * <pre>
     * 宠物同步信息
     * </pre>
     */
    java.util.List<? extends com.hawk.game.protocol.Monster.SynMonsterAttrOrBuilder> 
        getMonstersAttrOrBuilderList();
    /**
     * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
     *
     * <pre>
     * 宠物同步信息
     * </pre>
     */
    com.hawk.game.protocol.Monster.SynMonsterAttrOrBuilder getMonstersAttrOrBuilder(
        int index);

    // repeated .ConsumeItem consumeItems = 3;
    /**
     * <code>repeated .ConsumeItem consumeItems = 3;</code>
     *
     * <pre>
     * 移除的物品 
     * </pre>
     */
    java.util.List<com.hawk.game.protocol.Consume.ConsumeItem> 
        getConsumeItemsList();
    /**
     * <code>repeated .ConsumeItem consumeItems = 3;</code>
     *
     * <pre>
     * 移除的物品 
     * </pre>
     */
    com.hawk.game.protocol.Consume.ConsumeItem getConsumeItems(int index);
    /**
     * <code>repeated .ConsumeItem consumeItems = 3;</code>
     *
     * <pre>
     * 移除的物品 
     * </pre>
     */
    int getConsumeItemsCount();
    /**
     * <code>repeated .ConsumeItem consumeItems = 3;</code>
     *
     * <pre>
     * 移除的物品 
     * </pre>
     */
    java.util.List<? extends com.hawk.game.protocol.Consume.ConsumeItemOrBuilder> 
        getConsumeItemsOrBuilderList();
    /**
     * <code>repeated .ConsumeItem consumeItems = 3;</code>
     *
     * <pre>
     * 移除的物品 
     * </pre>
     */
    com.hawk.game.protocol.Consume.ConsumeItemOrBuilder getConsumeItemsOrBuilder(
        int index);

    // optional int32 hsCode = 4;
    /**
     * <code>optional int32 hsCode = 4;</code>
     */
    boolean hasHsCode();
    /**
     * <code>optional int32 hsCode = 4;</code>
     */
    int getHsCode();
  }
  /**
   * Protobuf type {@code HSConsumeInfo}
   *
   * <pre>
   * 经常发生变动的值主动推送给前端
   * </pre>
   */
  public static final class HSConsumeInfo extends
      com.google.protobuf.GeneratedMessage
      implements HSConsumeInfoOrBuilder {
    // Use HSConsumeInfo.newBuilder() to construct.
    private HSConsumeInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HSConsumeInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HSConsumeInfo defaultInstance;
    public static HSConsumeInfo getDefaultInstance() {
      return defaultInstance;
    }

    public HSConsumeInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HSConsumeInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.hawk.game.protocol.Player.SynPlayerAttr.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = playerAttr_.toBuilder();
              }
              playerAttr_ = input.readMessage(com.hawk.game.protocol.Player.SynPlayerAttr.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(playerAttr_);
                playerAttr_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                monstersAttr_ = new java.util.ArrayList<com.hawk.game.protocol.Monster.SynMonsterAttr>();
                mutable_bitField0_ |= 0x00000002;
              }
              monstersAttr_.add(input.readMessage(com.hawk.game.protocol.Monster.SynMonsterAttr.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                consumeItems_ = new java.util.ArrayList<com.hawk.game.protocol.Consume.ConsumeItem>();
                mutable_bitField0_ |= 0x00000004;
              }
              consumeItems_.add(input.readMessage(com.hawk.game.protocol.Consume.ConsumeItem.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              hsCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          monstersAttr_ = java.util.Collections.unmodifiableList(monstersAttr_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          consumeItems_ = java.util.Collections.unmodifiableList(consumeItems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.Consume.internal_static_HSConsumeInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.Consume.internal_static_HSConsumeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.Consume.HSConsumeInfo.class, com.hawk.game.protocol.Consume.HSConsumeInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<HSConsumeInfo> PARSER =
        new com.google.protobuf.AbstractParser<HSConsumeInfo>() {
      public HSConsumeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HSConsumeInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HSConsumeInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .SynPlayerAttr playerAttr = 1;
    public static final int PLAYERATTR_FIELD_NUMBER = 1;
    private com.hawk.game.protocol.Player.SynPlayerAttr playerAttr_;
    /**
     * <code>optional .SynPlayerAttr playerAttr = 1;</code>
     *
     * <pre>
     * 玩家同步信息
     * </pre>
     */
    public boolean hasPlayerAttr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .SynPlayerAttr playerAttr = 1;</code>
     *
     * <pre>
     * 玩家同步信息
     * </pre>
     */
    public com.hawk.game.protocol.Player.SynPlayerAttr getPlayerAttr() {
      return playerAttr_;
    }
    /**
     * <code>optional .SynPlayerAttr playerAttr = 1;</code>
     *
     * <pre>
     * 玩家同步信息
     * </pre>
     */
    public com.hawk.game.protocol.Player.SynPlayerAttrOrBuilder getPlayerAttrOrBuilder() {
      return playerAttr_;
    }

    // repeated .SynMonsterAttr monstersAttr = 2;
    public static final int MONSTERSATTR_FIELD_NUMBER = 2;
    private java.util.List<com.hawk.game.protocol.Monster.SynMonsterAttr> monstersAttr_;
    /**
     * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
     *
     * <pre>
     * 宠物同步信息
     * </pre>
     */
    public java.util.List<com.hawk.game.protocol.Monster.SynMonsterAttr> getMonstersAttrList() {
      return monstersAttr_;
    }
    /**
     * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
     *
     * <pre>
     * 宠物同步信息
     * </pre>
     */
    public java.util.List<? extends com.hawk.game.protocol.Monster.SynMonsterAttrOrBuilder> 
        getMonstersAttrOrBuilderList() {
      return monstersAttr_;
    }
    /**
     * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
     *
     * <pre>
     * 宠物同步信息
     * </pre>
     */
    public int getMonstersAttrCount() {
      return monstersAttr_.size();
    }
    /**
     * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
     *
     * <pre>
     * 宠物同步信息
     * </pre>
     */
    public com.hawk.game.protocol.Monster.SynMonsterAttr getMonstersAttr(int index) {
      return monstersAttr_.get(index);
    }
    /**
     * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
     *
     * <pre>
     * 宠物同步信息
     * </pre>
     */
    public com.hawk.game.protocol.Monster.SynMonsterAttrOrBuilder getMonstersAttrOrBuilder(
        int index) {
      return monstersAttr_.get(index);
    }

    // repeated .ConsumeItem consumeItems = 3;
    public static final int CONSUMEITEMS_FIELD_NUMBER = 3;
    private java.util.List<com.hawk.game.protocol.Consume.ConsumeItem> consumeItems_;
    /**
     * <code>repeated .ConsumeItem consumeItems = 3;</code>
     *
     * <pre>
     * 移除的物品 
     * </pre>
     */
    public java.util.List<com.hawk.game.protocol.Consume.ConsumeItem> getConsumeItemsList() {
      return consumeItems_;
    }
    /**
     * <code>repeated .ConsumeItem consumeItems = 3;</code>
     *
     * <pre>
     * 移除的物品 
     * </pre>
     */
    public java.util.List<? extends com.hawk.game.protocol.Consume.ConsumeItemOrBuilder> 
        getConsumeItemsOrBuilderList() {
      return consumeItems_;
    }
    /**
     * <code>repeated .ConsumeItem consumeItems = 3;</code>
     *
     * <pre>
     * 移除的物品 
     * </pre>
     */
    public int getConsumeItemsCount() {
      return consumeItems_.size();
    }
    /**
     * <code>repeated .ConsumeItem consumeItems = 3;</code>
     *
     * <pre>
     * 移除的物品 
     * </pre>
     */
    public com.hawk.game.protocol.Consume.ConsumeItem getConsumeItems(int index) {
      return consumeItems_.get(index);
    }
    /**
     * <code>repeated .ConsumeItem consumeItems = 3;</code>
     *
     * <pre>
     * 移除的物品 
     * </pre>
     */
    public com.hawk.game.protocol.Consume.ConsumeItemOrBuilder getConsumeItemsOrBuilder(
        int index) {
      return consumeItems_.get(index);
    }

    // optional int32 hsCode = 4;
    public static final int HSCODE_FIELD_NUMBER = 4;
    private int hsCode_;
    /**
     * <code>optional int32 hsCode = 4;</code>
     */
    public boolean hasHsCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 hsCode = 4;</code>
     */
    public int getHsCode() {
      return hsCode_;
    }

    private void initFields() {
      playerAttr_ = com.hawk.game.protocol.Player.SynPlayerAttr.getDefaultInstance();
      monstersAttr_ = java.util.Collections.emptyList();
      consumeItems_ = java.util.Collections.emptyList();
      hsCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getMonstersAttrCount(); i++) {
        if (!getMonstersAttr(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getConsumeItemsCount(); i++) {
        if (!getConsumeItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, playerAttr_);
      }
      for (int i = 0; i < monstersAttr_.size(); i++) {
        output.writeMessage(2, monstersAttr_.get(i));
      }
      for (int i = 0; i < consumeItems_.size(); i++) {
        output.writeMessage(3, consumeItems_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(4, hsCode_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, playerAttr_);
      }
      for (int i = 0; i < monstersAttr_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, monstersAttr_.get(i));
      }
      for (int i = 0; i < consumeItems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, consumeItems_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, hsCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.Consume.HSConsumeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Consume.HSConsumeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Consume.HSConsumeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Consume.HSConsumeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Consume.HSConsumeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Consume.HSConsumeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Consume.HSConsumeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.Consume.HSConsumeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Consume.HSConsumeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Consume.HSConsumeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.Consume.HSConsumeInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HSConsumeInfo}
     *
     * <pre>
     * 经常发生变动的值主动推送给前端
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.Consume.HSConsumeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.Consume.internal_static_HSConsumeInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.Consume.internal_static_HSConsumeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.Consume.HSConsumeInfo.class, com.hawk.game.protocol.Consume.HSConsumeInfo.Builder.class);
      }

      // Construct using com.hawk.game.protocol.Consume.HSConsumeInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayerAttrFieldBuilder();
          getMonstersAttrFieldBuilder();
          getConsumeItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (playerAttrBuilder_ == null) {
          playerAttr_ = com.hawk.game.protocol.Player.SynPlayerAttr.getDefaultInstance();
        } else {
          playerAttrBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (monstersAttrBuilder_ == null) {
          monstersAttr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          monstersAttrBuilder_.clear();
        }
        if (consumeItemsBuilder_ == null) {
          consumeItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          consumeItemsBuilder_.clear();
        }
        hsCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.Consume.internal_static_HSConsumeInfo_descriptor;
      }

      public com.hawk.game.protocol.Consume.HSConsumeInfo getDefaultInstanceForType() {
        return com.hawk.game.protocol.Consume.HSConsumeInfo.getDefaultInstance();
      }

      public com.hawk.game.protocol.Consume.HSConsumeInfo build() {
        com.hawk.game.protocol.Consume.HSConsumeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.Consume.HSConsumeInfo buildPartial() {
        com.hawk.game.protocol.Consume.HSConsumeInfo result = new com.hawk.game.protocol.Consume.HSConsumeInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (playerAttrBuilder_ == null) {
          result.playerAttr_ = playerAttr_;
        } else {
          result.playerAttr_ = playerAttrBuilder_.build();
        }
        if (monstersAttrBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            monstersAttr_ = java.util.Collections.unmodifiableList(monstersAttr_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.monstersAttr_ = monstersAttr_;
        } else {
          result.monstersAttr_ = monstersAttrBuilder_.build();
        }
        if (consumeItemsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            consumeItems_ = java.util.Collections.unmodifiableList(consumeItems_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.consumeItems_ = consumeItems_;
        } else {
          result.consumeItems_ = consumeItemsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hsCode_ = hsCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.Consume.HSConsumeInfo) {
          return mergeFrom((com.hawk.game.protocol.Consume.HSConsumeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.Consume.HSConsumeInfo other) {
        if (other == com.hawk.game.protocol.Consume.HSConsumeInfo.getDefaultInstance()) return this;
        if (other.hasPlayerAttr()) {
          mergePlayerAttr(other.getPlayerAttr());
        }
        if (monstersAttrBuilder_ == null) {
          if (!other.monstersAttr_.isEmpty()) {
            if (monstersAttr_.isEmpty()) {
              monstersAttr_ = other.monstersAttr_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMonstersAttrIsMutable();
              monstersAttr_.addAll(other.monstersAttr_);
            }
            onChanged();
          }
        } else {
          if (!other.monstersAttr_.isEmpty()) {
            if (monstersAttrBuilder_.isEmpty()) {
              monstersAttrBuilder_.dispose();
              monstersAttrBuilder_ = null;
              monstersAttr_ = other.monstersAttr_;
              bitField0_ = (bitField0_ & ~0x00000002);
              monstersAttrBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMonstersAttrFieldBuilder() : null;
            } else {
              monstersAttrBuilder_.addAllMessages(other.monstersAttr_);
            }
          }
        }
        if (consumeItemsBuilder_ == null) {
          if (!other.consumeItems_.isEmpty()) {
            if (consumeItems_.isEmpty()) {
              consumeItems_ = other.consumeItems_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureConsumeItemsIsMutable();
              consumeItems_.addAll(other.consumeItems_);
            }
            onChanged();
          }
        } else {
          if (!other.consumeItems_.isEmpty()) {
            if (consumeItemsBuilder_.isEmpty()) {
              consumeItemsBuilder_.dispose();
              consumeItemsBuilder_ = null;
              consumeItems_ = other.consumeItems_;
              bitField0_ = (bitField0_ & ~0x00000004);
              consumeItemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getConsumeItemsFieldBuilder() : null;
            } else {
              consumeItemsBuilder_.addAllMessages(other.consumeItems_);
            }
          }
        }
        if (other.hasHsCode()) {
          setHsCode(other.getHsCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMonstersAttrCount(); i++) {
          if (!getMonstersAttr(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getConsumeItemsCount(); i++) {
          if (!getConsumeItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.Consume.HSConsumeInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.Consume.HSConsumeInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .SynPlayerAttr playerAttr = 1;
      private com.hawk.game.protocol.Player.SynPlayerAttr playerAttr_ = com.hawk.game.protocol.Player.SynPlayerAttr.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.hawk.game.protocol.Player.SynPlayerAttr, com.hawk.game.protocol.Player.SynPlayerAttr.Builder, com.hawk.game.protocol.Player.SynPlayerAttrOrBuilder> playerAttrBuilder_;
      /**
       * <code>optional .SynPlayerAttr playerAttr = 1;</code>
       *
       * <pre>
       * 玩家同步信息
       * </pre>
       */
      public boolean hasPlayerAttr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .SynPlayerAttr playerAttr = 1;</code>
       *
       * <pre>
       * 玩家同步信息
       * </pre>
       */
      public com.hawk.game.protocol.Player.SynPlayerAttr getPlayerAttr() {
        if (playerAttrBuilder_ == null) {
          return playerAttr_;
        } else {
          return playerAttrBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SynPlayerAttr playerAttr = 1;</code>
       *
       * <pre>
       * 玩家同步信息
       * </pre>
       */
      public Builder setPlayerAttr(com.hawk.game.protocol.Player.SynPlayerAttr value) {
        if (playerAttrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerAttr_ = value;
          onChanged();
        } else {
          playerAttrBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SynPlayerAttr playerAttr = 1;</code>
       *
       * <pre>
       * 玩家同步信息
       * </pre>
       */
      public Builder setPlayerAttr(
          com.hawk.game.protocol.Player.SynPlayerAttr.Builder builderForValue) {
        if (playerAttrBuilder_ == null) {
          playerAttr_ = builderForValue.build();
          onChanged();
        } else {
          playerAttrBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SynPlayerAttr playerAttr = 1;</code>
       *
       * <pre>
       * 玩家同步信息
       * </pre>
       */
      public Builder mergePlayerAttr(com.hawk.game.protocol.Player.SynPlayerAttr value) {
        if (playerAttrBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              playerAttr_ != com.hawk.game.protocol.Player.SynPlayerAttr.getDefaultInstance()) {
            playerAttr_ =
              com.hawk.game.protocol.Player.SynPlayerAttr.newBuilder(playerAttr_).mergeFrom(value).buildPartial();
          } else {
            playerAttr_ = value;
          }
          onChanged();
        } else {
          playerAttrBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SynPlayerAttr playerAttr = 1;</code>
       *
       * <pre>
       * 玩家同步信息
       * </pre>
       */
      public Builder clearPlayerAttr() {
        if (playerAttrBuilder_ == null) {
          playerAttr_ = com.hawk.game.protocol.Player.SynPlayerAttr.getDefaultInstance();
          onChanged();
        } else {
          playerAttrBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .SynPlayerAttr playerAttr = 1;</code>
       *
       * <pre>
       * 玩家同步信息
       * </pre>
       */
      public com.hawk.game.protocol.Player.SynPlayerAttr.Builder getPlayerAttrBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPlayerAttrFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SynPlayerAttr playerAttr = 1;</code>
       *
       * <pre>
       * 玩家同步信息
       * </pre>
       */
      public com.hawk.game.protocol.Player.SynPlayerAttrOrBuilder getPlayerAttrOrBuilder() {
        if (playerAttrBuilder_ != null) {
          return playerAttrBuilder_.getMessageOrBuilder();
        } else {
          return playerAttr_;
        }
      }
      /**
       * <code>optional .SynPlayerAttr playerAttr = 1;</code>
       *
       * <pre>
       * 玩家同步信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.hawk.game.protocol.Player.SynPlayerAttr, com.hawk.game.protocol.Player.SynPlayerAttr.Builder, com.hawk.game.protocol.Player.SynPlayerAttrOrBuilder> 
          getPlayerAttrFieldBuilder() {
        if (playerAttrBuilder_ == null) {
          playerAttrBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.hawk.game.protocol.Player.SynPlayerAttr, com.hawk.game.protocol.Player.SynPlayerAttr.Builder, com.hawk.game.protocol.Player.SynPlayerAttrOrBuilder>(
                  playerAttr_,
                  getParentForChildren(),
                  isClean());
          playerAttr_ = null;
        }
        return playerAttrBuilder_;
      }

      // repeated .SynMonsterAttr monstersAttr = 2;
      private java.util.List<com.hawk.game.protocol.Monster.SynMonsterAttr> monstersAttr_ =
        java.util.Collections.emptyList();
      private void ensureMonstersAttrIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          monstersAttr_ = new java.util.ArrayList<com.hawk.game.protocol.Monster.SynMonsterAttr>(monstersAttr_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.Monster.SynMonsterAttr, com.hawk.game.protocol.Monster.SynMonsterAttr.Builder, com.hawk.game.protocol.Monster.SynMonsterAttrOrBuilder> monstersAttrBuilder_;

      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public java.util.List<com.hawk.game.protocol.Monster.SynMonsterAttr> getMonstersAttrList() {
        if (monstersAttrBuilder_ == null) {
          return java.util.Collections.unmodifiableList(monstersAttr_);
        } else {
          return monstersAttrBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public int getMonstersAttrCount() {
        if (monstersAttrBuilder_ == null) {
          return monstersAttr_.size();
        } else {
          return monstersAttrBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public com.hawk.game.protocol.Monster.SynMonsterAttr getMonstersAttr(int index) {
        if (monstersAttrBuilder_ == null) {
          return monstersAttr_.get(index);
        } else {
          return monstersAttrBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public Builder setMonstersAttr(
          int index, com.hawk.game.protocol.Monster.SynMonsterAttr value) {
        if (monstersAttrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonstersAttrIsMutable();
          monstersAttr_.set(index, value);
          onChanged();
        } else {
          monstersAttrBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public Builder setMonstersAttr(
          int index, com.hawk.game.protocol.Monster.SynMonsterAttr.Builder builderForValue) {
        if (monstersAttrBuilder_ == null) {
          ensureMonstersAttrIsMutable();
          monstersAttr_.set(index, builderForValue.build());
          onChanged();
        } else {
          monstersAttrBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public Builder addMonstersAttr(com.hawk.game.protocol.Monster.SynMonsterAttr value) {
        if (monstersAttrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonstersAttrIsMutable();
          monstersAttr_.add(value);
          onChanged();
        } else {
          monstersAttrBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public Builder addMonstersAttr(
          int index, com.hawk.game.protocol.Monster.SynMonsterAttr value) {
        if (monstersAttrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonstersAttrIsMutable();
          monstersAttr_.add(index, value);
          onChanged();
        } else {
          monstersAttrBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public Builder addMonstersAttr(
          com.hawk.game.protocol.Monster.SynMonsterAttr.Builder builderForValue) {
        if (monstersAttrBuilder_ == null) {
          ensureMonstersAttrIsMutable();
          monstersAttr_.add(builderForValue.build());
          onChanged();
        } else {
          monstersAttrBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public Builder addMonstersAttr(
          int index, com.hawk.game.protocol.Monster.SynMonsterAttr.Builder builderForValue) {
        if (monstersAttrBuilder_ == null) {
          ensureMonstersAttrIsMutable();
          monstersAttr_.add(index, builderForValue.build());
          onChanged();
        } else {
          monstersAttrBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public Builder addAllMonstersAttr(
          java.lang.Iterable<? extends com.hawk.game.protocol.Monster.SynMonsterAttr> values) {
        if (monstersAttrBuilder_ == null) {
          ensureMonstersAttrIsMutable();
          super.addAll(values, monstersAttr_);
          onChanged();
        } else {
          monstersAttrBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public Builder clearMonstersAttr() {
        if (monstersAttrBuilder_ == null) {
          monstersAttr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          monstersAttrBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public Builder removeMonstersAttr(int index) {
        if (monstersAttrBuilder_ == null) {
          ensureMonstersAttrIsMutable();
          monstersAttr_.remove(index);
          onChanged();
        } else {
          monstersAttrBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public com.hawk.game.protocol.Monster.SynMonsterAttr.Builder getMonstersAttrBuilder(
          int index) {
        return getMonstersAttrFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public com.hawk.game.protocol.Monster.SynMonsterAttrOrBuilder getMonstersAttrOrBuilder(
          int index) {
        if (monstersAttrBuilder_ == null) {
          return monstersAttr_.get(index);  } else {
          return monstersAttrBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public java.util.List<? extends com.hawk.game.protocol.Monster.SynMonsterAttrOrBuilder> 
           getMonstersAttrOrBuilderList() {
        if (monstersAttrBuilder_ != null) {
          return monstersAttrBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(monstersAttr_);
        }
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public com.hawk.game.protocol.Monster.SynMonsterAttr.Builder addMonstersAttrBuilder() {
        return getMonstersAttrFieldBuilder().addBuilder(
            com.hawk.game.protocol.Monster.SynMonsterAttr.getDefaultInstance());
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public com.hawk.game.protocol.Monster.SynMonsterAttr.Builder addMonstersAttrBuilder(
          int index) {
        return getMonstersAttrFieldBuilder().addBuilder(
            index, com.hawk.game.protocol.Monster.SynMonsterAttr.getDefaultInstance());
      }
      /**
       * <code>repeated .SynMonsterAttr monstersAttr = 2;</code>
       *
       * <pre>
       * 宠物同步信息
       * </pre>
       */
      public java.util.List<com.hawk.game.protocol.Monster.SynMonsterAttr.Builder> 
           getMonstersAttrBuilderList() {
        return getMonstersAttrFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.Monster.SynMonsterAttr, com.hawk.game.protocol.Monster.SynMonsterAttr.Builder, com.hawk.game.protocol.Monster.SynMonsterAttrOrBuilder> 
          getMonstersAttrFieldBuilder() {
        if (monstersAttrBuilder_ == null) {
          monstersAttrBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hawk.game.protocol.Monster.SynMonsterAttr, com.hawk.game.protocol.Monster.SynMonsterAttr.Builder, com.hawk.game.protocol.Monster.SynMonsterAttrOrBuilder>(
                  monstersAttr_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          monstersAttr_ = null;
        }
        return monstersAttrBuilder_;
      }

      // repeated .ConsumeItem consumeItems = 3;
      private java.util.List<com.hawk.game.protocol.Consume.ConsumeItem> consumeItems_ =
        java.util.Collections.emptyList();
      private void ensureConsumeItemsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          consumeItems_ = new java.util.ArrayList<com.hawk.game.protocol.Consume.ConsumeItem>(consumeItems_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.Consume.ConsumeItem, com.hawk.game.protocol.Consume.ConsumeItem.Builder, com.hawk.game.protocol.Consume.ConsumeItemOrBuilder> consumeItemsBuilder_;

      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public java.util.List<com.hawk.game.protocol.Consume.ConsumeItem> getConsumeItemsList() {
        if (consumeItemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(consumeItems_);
        } else {
          return consumeItemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public int getConsumeItemsCount() {
        if (consumeItemsBuilder_ == null) {
          return consumeItems_.size();
        } else {
          return consumeItemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public com.hawk.game.protocol.Consume.ConsumeItem getConsumeItems(int index) {
        if (consumeItemsBuilder_ == null) {
          return consumeItems_.get(index);
        } else {
          return consumeItemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public Builder setConsumeItems(
          int index, com.hawk.game.protocol.Consume.ConsumeItem value) {
        if (consumeItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConsumeItemsIsMutable();
          consumeItems_.set(index, value);
          onChanged();
        } else {
          consumeItemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public Builder setConsumeItems(
          int index, com.hawk.game.protocol.Consume.ConsumeItem.Builder builderForValue) {
        if (consumeItemsBuilder_ == null) {
          ensureConsumeItemsIsMutable();
          consumeItems_.set(index, builderForValue.build());
          onChanged();
        } else {
          consumeItemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public Builder addConsumeItems(com.hawk.game.protocol.Consume.ConsumeItem value) {
        if (consumeItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConsumeItemsIsMutable();
          consumeItems_.add(value);
          onChanged();
        } else {
          consumeItemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public Builder addConsumeItems(
          int index, com.hawk.game.protocol.Consume.ConsumeItem value) {
        if (consumeItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConsumeItemsIsMutable();
          consumeItems_.add(index, value);
          onChanged();
        } else {
          consumeItemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public Builder addConsumeItems(
          com.hawk.game.protocol.Consume.ConsumeItem.Builder builderForValue) {
        if (consumeItemsBuilder_ == null) {
          ensureConsumeItemsIsMutable();
          consumeItems_.add(builderForValue.build());
          onChanged();
        } else {
          consumeItemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public Builder addConsumeItems(
          int index, com.hawk.game.protocol.Consume.ConsumeItem.Builder builderForValue) {
        if (consumeItemsBuilder_ == null) {
          ensureConsumeItemsIsMutable();
          consumeItems_.add(index, builderForValue.build());
          onChanged();
        } else {
          consumeItemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public Builder addAllConsumeItems(
          java.lang.Iterable<? extends com.hawk.game.protocol.Consume.ConsumeItem> values) {
        if (consumeItemsBuilder_ == null) {
          ensureConsumeItemsIsMutable();
          super.addAll(values, consumeItems_);
          onChanged();
        } else {
          consumeItemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public Builder clearConsumeItems() {
        if (consumeItemsBuilder_ == null) {
          consumeItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          consumeItemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public Builder removeConsumeItems(int index) {
        if (consumeItemsBuilder_ == null) {
          ensureConsumeItemsIsMutable();
          consumeItems_.remove(index);
          onChanged();
        } else {
          consumeItemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public com.hawk.game.protocol.Consume.ConsumeItem.Builder getConsumeItemsBuilder(
          int index) {
        return getConsumeItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public com.hawk.game.protocol.Consume.ConsumeItemOrBuilder getConsumeItemsOrBuilder(
          int index) {
        if (consumeItemsBuilder_ == null) {
          return consumeItems_.get(index);  } else {
          return consumeItemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public java.util.List<? extends com.hawk.game.protocol.Consume.ConsumeItemOrBuilder> 
           getConsumeItemsOrBuilderList() {
        if (consumeItemsBuilder_ != null) {
          return consumeItemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(consumeItems_);
        }
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public com.hawk.game.protocol.Consume.ConsumeItem.Builder addConsumeItemsBuilder() {
        return getConsumeItemsFieldBuilder().addBuilder(
            com.hawk.game.protocol.Consume.ConsumeItem.getDefaultInstance());
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public com.hawk.game.protocol.Consume.ConsumeItem.Builder addConsumeItemsBuilder(
          int index) {
        return getConsumeItemsFieldBuilder().addBuilder(
            index, com.hawk.game.protocol.Consume.ConsumeItem.getDefaultInstance());
      }
      /**
       * <code>repeated .ConsumeItem consumeItems = 3;</code>
       *
       * <pre>
       * 移除的物品 
       * </pre>
       */
      public java.util.List<com.hawk.game.protocol.Consume.ConsumeItem.Builder> 
           getConsumeItemsBuilderList() {
        return getConsumeItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.Consume.ConsumeItem, com.hawk.game.protocol.Consume.ConsumeItem.Builder, com.hawk.game.protocol.Consume.ConsumeItemOrBuilder> 
          getConsumeItemsFieldBuilder() {
        if (consumeItemsBuilder_ == null) {
          consumeItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hawk.game.protocol.Consume.ConsumeItem, com.hawk.game.protocol.Consume.ConsumeItem.Builder, com.hawk.game.protocol.Consume.ConsumeItemOrBuilder>(
                  consumeItems_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          consumeItems_ = null;
        }
        return consumeItemsBuilder_;
      }

      // optional int32 hsCode = 4;
      private int hsCode_ ;
      /**
       * <code>optional int32 hsCode = 4;</code>
       */
      public boolean hasHsCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 hsCode = 4;</code>
       */
      public int getHsCode() {
        return hsCode_;
      }
      /**
       * <code>optional int32 hsCode = 4;</code>
       */
      public Builder setHsCode(int value) {
        bitField0_ |= 0x00000008;
        hsCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hsCode = 4;</code>
       */
      public Builder clearHsCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hsCode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HSConsumeInfo)
    }

    static {
      defaultInstance = new HSConsumeInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HSConsumeInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ConsumeItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ConsumeItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HSConsumeInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HSConsumeInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026Protocol/Consume.proto\032\025Protocol/Playe" +
      "r.proto\032\026Protocol/Monster.proto\"F\n\013Consu" +
      "meItem\022\014\n\004type\030\001 \002(\005\022\n\n\002id\030\002 \001(\003\022\016\n\006item" +
      "Id\030\003 \002(\t\022\r\n\005count\030\004 \001(\003\"\216\001\n\rHSConsumeInf" +
      "o\022\"\n\nplayerAttr\030\001 \001(\0132\016.SynPlayerAttr\022%\n" +
      "\014monstersAttr\030\002 \003(\0132\017.SynMonsterAttr\022\"\n\014" +
      "consumeItems\030\003 \003(\0132\014.ConsumeItem\022\016\n\006hsCo" +
      "de\030\004 \001(\005B\030\n\026com.hawk.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ConsumeItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ConsumeItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ConsumeItem_descriptor,
              new java.lang.String[] { "Type", "Id", "ItemId", "Count", });
          internal_static_HSConsumeInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HSConsumeInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HSConsumeInfo_descriptor,
              new java.lang.String[] { "PlayerAttr", "MonstersAttr", "ConsumeItems", "HsCode", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hawk.game.protocol.Player.getDescriptor(),
          com.hawk.game.protocol.Monster.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
