// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol/Statistics.proto

package com.hawk.game.protocol;

public final class Statistics {
  private Statistics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InstanceStateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string instanceId = 1;
    /**
     * <code>required string instanceId = 1;</code>
     */
    boolean hasInstanceId();
    /**
     * <code>required string instanceId = 1;</code>
     */
    java.lang.String getInstanceId();
    /**
     * <code>required string instanceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getInstanceIdBytes();

    // required int32 star = 2;
    /**
     * <code>required int32 star = 2;</code>
     */
    boolean hasStar();
    /**
     * <code>required int32 star = 2;</code>
     */
    int getStar();

    // optional int32 countDaily = 3;
    /**
     * <code>optional int32 countDaily = 3;</code>
     */
    boolean hasCountDaily();
    /**
     * <code>optional int32 countDaily = 3;</code>
     */
    int getCountDaily();
  }
  /**
   * Protobuf type {@code InstanceState}
   */
  public static final class InstanceState extends
      com.google.protobuf.GeneratedMessage
      implements InstanceStateOrBuilder {
    // Use InstanceState.newBuilder() to construct.
    private InstanceState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InstanceState(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InstanceState defaultInstance;
    public static InstanceState getDefaultInstance() {
      return defaultInstance;
    }

    public InstanceState getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InstanceState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              instanceId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              star_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              countDaily_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.Statistics.internal_static_InstanceState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.Statistics.internal_static_InstanceState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.Statistics.InstanceState.class, com.hawk.game.protocol.Statistics.InstanceState.Builder.class);
    }

    public static com.google.protobuf.Parser<InstanceState> PARSER =
        new com.google.protobuf.AbstractParser<InstanceState>() {
      public InstanceState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InstanceState(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InstanceState> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string instanceId = 1;
    public static final int INSTANCEID_FIELD_NUMBER = 1;
    private java.lang.Object instanceId_;
    /**
     * <code>required string instanceId = 1;</code>
     */
    public boolean hasInstanceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string instanceId = 1;</code>
     */
    public java.lang.String getInstanceId() {
      java.lang.Object ref = instanceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          instanceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string instanceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInstanceIdBytes() {
      java.lang.Object ref = instanceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 star = 2;
    public static final int STAR_FIELD_NUMBER = 2;
    private int star_;
    /**
     * <code>required int32 star = 2;</code>
     */
    public boolean hasStar() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 star = 2;</code>
     */
    public int getStar() {
      return star_;
    }

    // optional int32 countDaily = 3;
    public static final int COUNTDAILY_FIELD_NUMBER = 3;
    private int countDaily_;
    /**
     * <code>optional int32 countDaily = 3;</code>
     */
    public boolean hasCountDaily() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 countDaily = 3;</code>
     */
    public int getCountDaily() {
      return countDaily_;
    }

    private void initFields() {
      instanceId_ = "";
      star_ = 0;
      countDaily_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasInstanceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStar()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getInstanceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, star_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, countDaily_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getInstanceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, star_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, countDaily_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.Statistics.InstanceState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Statistics.InstanceState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Statistics.InstanceState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Statistics.InstanceState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Statistics.InstanceState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Statistics.InstanceState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Statistics.InstanceState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.Statistics.InstanceState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Statistics.InstanceState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Statistics.InstanceState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.Statistics.InstanceState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InstanceState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.Statistics.InstanceStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.Statistics.internal_static_InstanceState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.Statistics.internal_static_InstanceState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.Statistics.InstanceState.class, com.hawk.game.protocol.Statistics.InstanceState.Builder.class);
      }

      // Construct using com.hawk.game.protocol.Statistics.InstanceState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        instanceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        star_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        countDaily_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.Statistics.internal_static_InstanceState_descriptor;
      }

      public com.hawk.game.protocol.Statistics.InstanceState getDefaultInstanceForType() {
        return com.hawk.game.protocol.Statistics.InstanceState.getDefaultInstance();
      }

      public com.hawk.game.protocol.Statistics.InstanceState build() {
        com.hawk.game.protocol.Statistics.InstanceState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.Statistics.InstanceState buildPartial() {
        com.hawk.game.protocol.Statistics.InstanceState result = new com.hawk.game.protocol.Statistics.InstanceState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.instanceId_ = instanceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.star_ = star_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.countDaily_ = countDaily_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.Statistics.InstanceState) {
          return mergeFrom((com.hawk.game.protocol.Statistics.InstanceState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.Statistics.InstanceState other) {
        if (other == com.hawk.game.protocol.Statistics.InstanceState.getDefaultInstance()) return this;
        if (other.hasInstanceId()) {
          bitField0_ |= 0x00000001;
          instanceId_ = other.instanceId_;
          onChanged();
        }
        if (other.hasStar()) {
          setStar(other.getStar());
        }
        if (other.hasCountDaily()) {
          setCountDaily(other.getCountDaily());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInstanceId()) {
          
          return false;
        }
        if (!hasStar()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.Statistics.InstanceState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.Statistics.InstanceState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string instanceId = 1;
      private java.lang.Object instanceId_ = "";
      /**
       * <code>required string instanceId = 1;</code>
       */
      public boolean hasInstanceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string instanceId = 1;</code>
       */
      public java.lang.String getInstanceId() {
        java.lang.Object ref = instanceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          instanceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string instanceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInstanceIdBytes() {
        java.lang.Object ref = instanceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instanceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string instanceId = 1;</code>
       */
      public Builder setInstanceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        instanceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string instanceId = 1;</code>
       */
      public Builder clearInstanceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        instanceId_ = getDefaultInstance().getInstanceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string instanceId = 1;</code>
       */
      public Builder setInstanceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        instanceId_ = value;
        onChanged();
        return this;
      }

      // required int32 star = 2;
      private int star_ ;
      /**
       * <code>required int32 star = 2;</code>
       */
      public boolean hasStar() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 star = 2;</code>
       */
      public int getStar() {
        return star_;
      }
      /**
       * <code>required int32 star = 2;</code>
       */
      public Builder setStar(int value) {
        bitField0_ |= 0x00000002;
        star_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 star = 2;</code>
       */
      public Builder clearStar() {
        bitField0_ = (bitField0_ & ~0x00000002);
        star_ = 0;
        onChanged();
        return this;
      }

      // optional int32 countDaily = 3;
      private int countDaily_ ;
      /**
       * <code>optional int32 countDaily = 3;</code>
       */
      public boolean hasCountDaily() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 countDaily = 3;</code>
       */
      public int getCountDaily() {
        return countDaily_;
      }
      /**
       * <code>optional int32 countDaily = 3;</code>
       */
      public Builder setCountDaily(int value) {
        bitField0_ |= 0x00000004;
        countDaily_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 countDaily = 3;</code>
       */
      public Builder clearCountDaily() {
        bitField0_ = (bitField0_ & ~0x00000004);
        countDaily_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InstanceState)
    }

    static {
      defaultInstance = new InstanceState(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:InstanceState)
  }

  public interface HSStatisticsInfoSyncOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .InstanceState instanceState = 1;
    /**
     * <code>repeated .InstanceState instanceState = 1;</code>
     *
     * <pre>
     * 副本状态
     * </pre>
     */
    java.util.List<com.hawk.game.protocol.Statistics.InstanceState> 
        getInstanceStateList();
    /**
     * <code>repeated .InstanceState instanceState = 1;</code>
     *
     * <pre>
     * 副本状态
     * </pre>
     */
    com.hawk.game.protocol.Statistics.InstanceState getInstanceState(int index);
    /**
     * <code>repeated .InstanceState instanceState = 1;</code>
     *
     * <pre>
     * 副本状态
     * </pre>
     */
    int getInstanceStateCount();
    /**
     * <code>repeated .InstanceState instanceState = 1;</code>
     *
     * <pre>
     * 副本状态
     * </pre>
     */
    java.util.List<? extends com.hawk.game.protocol.Statistics.InstanceStateOrBuilder> 
        getInstanceStateOrBuilderList();
    /**
     * <code>repeated .InstanceState instanceState = 1;</code>
     *
     * <pre>
     * 副本状态
     * </pre>
     */
    com.hawk.game.protocol.Statistics.InstanceStateOrBuilder getInstanceStateOrBuilder(
        int index);

    // repeated string monsterCollect = 2;
    /**
     * <code>repeated string monsterCollect = 2;</code>
     *
     * <pre>
     * 宠物图鉴
     * </pre>
     */
    java.util.List<java.lang.String>
    getMonsterCollectList();
    /**
     * <code>repeated string monsterCollect = 2;</code>
     *
     * <pre>
     * 宠物图鉴
     * </pre>
     */
    int getMonsterCollectCount();
    /**
     * <code>repeated string monsterCollect = 2;</code>
     *
     * <pre>
     * 宠物图鉴
     * </pre>
     */
    java.lang.String getMonsterCollect(int index);
    /**
     * <code>repeated string monsterCollect = 2;</code>
     *
     * <pre>
     * 宠物图鉴
     * </pre>
     */
    com.google.protobuf.ByteString
        getMonsterCollectBytes(int index);

    // required int32 skillPoint = 3;
    /**
     * <code>required int32 skillPoint = 3;</code>
     *
     * <pre>
     * 当前技能点
     * </pre>
     */
    boolean hasSkillPoint();
    /**
     * <code>required int32 skillPoint = 3;</code>
     *
     * <pre>
     * 当前技能点
     * </pre>
     */
    int getSkillPoint();

    // required int32 skillPointTimeStamp = 4;
    /**
     * <code>required int32 skillPointTimeStamp = 4;</code>
     *
     * <pre>
     * 下个技能点开始计时时间戳
     * </pre>
     */
    boolean hasSkillPointTimeStamp();
    /**
     * <code>required int32 skillPointTimeStamp = 4;</code>
     *
     * <pre>
     * 下个技能点开始计时时间戳
     * </pre>
     */
    int getSkillPointTimeStamp();

    // optional int32 timeStamp = 5;
    /**
     * <code>optional int32 timeStamp = 5;</code>
     *
     * <pre>
     * 服务器时间戳
     * </pre>
     */
    boolean hasTimeStamp();
    /**
     * <code>optional int32 timeStamp = 5;</code>
     *
     * <pre>
     * 服务器时间戳
     * </pre>
     */
    int getTimeStamp();
  }
  /**
   * Protobuf type {@code HSStatisticsInfoSync}
   */
  public static final class HSStatisticsInfoSync extends
      com.google.protobuf.GeneratedMessage
      implements HSStatisticsInfoSyncOrBuilder {
    // Use HSStatisticsInfoSync.newBuilder() to construct.
    private HSStatisticsInfoSync(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HSStatisticsInfoSync(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HSStatisticsInfoSync defaultInstance;
    public static HSStatisticsInfoSync getDefaultInstance() {
      return defaultInstance;
    }

    public HSStatisticsInfoSync getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HSStatisticsInfoSync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                instanceState_ = new java.util.ArrayList<com.hawk.game.protocol.Statistics.InstanceState>();
                mutable_bitField0_ |= 0x00000001;
              }
              instanceState_.add(input.readMessage(com.hawk.game.protocol.Statistics.InstanceState.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                monsterCollect_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              monsterCollect_.add(input.readBytes());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000001;
              skillPoint_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              skillPointTimeStamp_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              timeStamp_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          instanceState_ = java.util.Collections.unmodifiableList(instanceState_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          monsterCollect_ = new com.google.protobuf.UnmodifiableLazyStringList(monsterCollect_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.Statistics.internal_static_HSStatisticsInfoSync_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.Statistics.internal_static_HSStatisticsInfoSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.Statistics.HSStatisticsInfoSync.class, com.hawk.game.protocol.Statistics.HSStatisticsInfoSync.Builder.class);
    }

    public static com.google.protobuf.Parser<HSStatisticsInfoSync> PARSER =
        new com.google.protobuf.AbstractParser<HSStatisticsInfoSync>() {
      public HSStatisticsInfoSync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HSStatisticsInfoSync(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HSStatisticsInfoSync> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .InstanceState instanceState = 1;
    public static final int INSTANCESTATE_FIELD_NUMBER = 1;
    private java.util.List<com.hawk.game.protocol.Statistics.InstanceState> instanceState_;
    /**
     * <code>repeated .InstanceState instanceState = 1;</code>
     *
     * <pre>
     * 副本状态
     * </pre>
     */
    public java.util.List<com.hawk.game.protocol.Statistics.InstanceState> getInstanceStateList() {
      return instanceState_;
    }
    /**
     * <code>repeated .InstanceState instanceState = 1;</code>
     *
     * <pre>
     * 副本状态
     * </pre>
     */
    public java.util.List<? extends com.hawk.game.protocol.Statistics.InstanceStateOrBuilder> 
        getInstanceStateOrBuilderList() {
      return instanceState_;
    }
    /**
     * <code>repeated .InstanceState instanceState = 1;</code>
     *
     * <pre>
     * 副本状态
     * </pre>
     */
    public int getInstanceStateCount() {
      return instanceState_.size();
    }
    /**
     * <code>repeated .InstanceState instanceState = 1;</code>
     *
     * <pre>
     * 副本状态
     * </pre>
     */
    public com.hawk.game.protocol.Statistics.InstanceState getInstanceState(int index) {
      return instanceState_.get(index);
    }
    /**
     * <code>repeated .InstanceState instanceState = 1;</code>
     *
     * <pre>
     * 副本状态
     * </pre>
     */
    public com.hawk.game.protocol.Statistics.InstanceStateOrBuilder getInstanceStateOrBuilder(
        int index) {
      return instanceState_.get(index);
    }

    // repeated string monsterCollect = 2;
    public static final int MONSTERCOLLECT_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList monsterCollect_;
    /**
     * <code>repeated string monsterCollect = 2;</code>
     *
     * <pre>
     * 宠物图鉴
     * </pre>
     */
    public java.util.List<java.lang.String>
        getMonsterCollectList() {
      return monsterCollect_;
    }
    /**
     * <code>repeated string monsterCollect = 2;</code>
     *
     * <pre>
     * 宠物图鉴
     * </pre>
     */
    public int getMonsterCollectCount() {
      return monsterCollect_.size();
    }
    /**
     * <code>repeated string monsterCollect = 2;</code>
     *
     * <pre>
     * 宠物图鉴
     * </pre>
     */
    public java.lang.String getMonsterCollect(int index) {
      return monsterCollect_.get(index);
    }
    /**
     * <code>repeated string monsterCollect = 2;</code>
     *
     * <pre>
     * 宠物图鉴
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMonsterCollectBytes(int index) {
      return monsterCollect_.getByteString(index);
    }

    // required int32 skillPoint = 3;
    public static final int SKILLPOINT_FIELD_NUMBER = 3;
    private int skillPoint_;
    /**
     * <code>required int32 skillPoint = 3;</code>
     *
     * <pre>
     * 当前技能点
     * </pre>
     */
    public boolean hasSkillPoint() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 skillPoint = 3;</code>
     *
     * <pre>
     * 当前技能点
     * </pre>
     */
    public int getSkillPoint() {
      return skillPoint_;
    }

    // required int32 skillPointTimeStamp = 4;
    public static final int SKILLPOINTTIMESTAMP_FIELD_NUMBER = 4;
    private int skillPointTimeStamp_;
    /**
     * <code>required int32 skillPointTimeStamp = 4;</code>
     *
     * <pre>
     * 下个技能点开始计时时间戳
     * </pre>
     */
    public boolean hasSkillPointTimeStamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 skillPointTimeStamp = 4;</code>
     *
     * <pre>
     * 下个技能点开始计时时间戳
     * </pre>
     */
    public int getSkillPointTimeStamp() {
      return skillPointTimeStamp_;
    }

    // optional int32 timeStamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private int timeStamp_;
    /**
     * <code>optional int32 timeStamp = 5;</code>
     *
     * <pre>
     * 服务器时间戳
     * </pre>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 timeStamp = 5;</code>
     *
     * <pre>
     * 服务器时间戳
     * </pre>
     */
    public int getTimeStamp() {
      return timeStamp_;
    }

    private void initFields() {
      instanceState_ = java.util.Collections.emptyList();
      monsterCollect_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      skillPoint_ = 0;
      skillPointTimeStamp_ = 0;
      timeStamp_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSkillPoint()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSkillPointTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getInstanceStateCount(); i++) {
        if (!getInstanceState(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < instanceState_.size(); i++) {
        output.writeMessage(1, instanceState_.get(i));
      }
      for (int i = 0; i < monsterCollect_.size(); i++) {
        output.writeBytes(2, monsterCollect_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(3, skillPoint_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(4, skillPointTimeStamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(5, timeStamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < instanceState_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, instanceState_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < monsterCollect_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(monsterCollect_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMonsterCollectList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, skillPoint_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, skillPointTimeStamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, timeStamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.Statistics.HSStatisticsInfoSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Statistics.HSStatisticsInfoSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Statistics.HSStatisticsInfoSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Statistics.HSStatisticsInfoSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Statistics.HSStatisticsInfoSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Statistics.HSStatisticsInfoSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Statistics.HSStatisticsInfoSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.Statistics.HSStatisticsInfoSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Statistics.HSStatisticsInfoSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Statistics.HSStatisticsInfoSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.Statistics.HSStatisticsInfoSync prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HSStatisticsInfoSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.Statistics.HSStatisticsInfoSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.Statistics.internal_static_HSStatisticsInfoSync_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.Statistics.internal_static_HSStatisticsInfoSync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.Statistics.HSStatisticsInfoSync.class, com.hawk.game.protocol.Statistics.HSStatisticsInfoSync.Builder.class);
      }

      // Construct using com.hawk.game.protocol.Statistics.HSStatisticsInfoSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInstanceStateFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (instanceStateBuilder_ == null) {
          instanceState_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          instanceStateBuilder_.clear();
        }
        monsterCollect_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        skillPoint_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        skillPointTimeStamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        timeStamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.Statistics.internal_static_HSStatisticsInfoSync_descriptor;
      }

      public com.hawk.game.protocol.Statistics.HSStatisticsInfoSync getDefaultInstanceForType() {
        return com.hawk.game.protocol.Statistics.HSStatisticsInfoSync.getDefaultInstance();
      }

      public com.hawk.game.protocol.Statistics.HSStatisticsInfoSync build() {
        com.hawk.game.protocol.Statistics.HSStatisticsInfoSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.Statistics.HSStatisticsInfoSync buildPartial() {
        com.hawk.game.protocol.Statistics.HSStatisticsInfoSync result = new com.hawk.game.protocol.Statistics.HSStatisticsInfoSync(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (instanceStateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            instanceState_ = java.util.Collections.unmodifiableList(instanceState_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.instanceState_ = instanceState_;
        } else {
          result.instanceState_ = instanceStateBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          monsterCollect_ = new com.google.protobuf.UnmodifiableLazyStringList(
              monsterCollect_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.monsterCollect_ = monsterCollect_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000001;
        }
        result.skillPoint_ = skillPoint_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.skillPointTimeStamp_ = skillPointTimeStamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeStamp_ = timeStamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.Statistics.HSStatisticsInfoSync) {
          return mergeFrom((com.hawk.game.protocol.Statistics.HSStatisticsInfoSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.Statistics.HSStatisticsInfoSync other) {
        if (other == com.hawk.game.protocol.Statistics.HSStatisticsInfoSync.getDefaultInstance()) return this;
        if (instanceStateBuilder_ == null) {
          if (!other.instanceState_.isEmpty()) {
            if (instanceState_.isEmpty()) {
              instanceState_ = other.instanceState_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInstanceStateIsMutable();
              instanceState_.addAll(other.instanceState_);
            }
            onChanged();
          }
        } else {
          if (!other.instanceState_.isEmpty()) {
            if (instanceStateBuilder_.isEmpty()) {
              instanceStateBuilder_.dispose();
              instanceStateBuilder_ = null;
              instanceState_ = other.instanceState_;
              bitField0_ = (bitField0_ & ~0x00000001);
              instanceStateBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInstanceStateFieldBuilder() : null;
            } else {
              instanceStateBuilder_.addAllMessages(other.instanceState_);
            }
          }
        }
        if (!other.monsterCollect_.isEmpty()) {
          if (monsterCollect_.isEmpty()) {
            monsterCollect_ = other.monsterCollect_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMonsterCollectIsMutable();
            monsterCollect_.addAll(other.monsterCollect_);
          }
          onChanged();
        }
        if (other.hasSkillPoint()) {
          setSkillPoint(other.getSkillPoint());
        }
        if (other.hasSkillPointTimeStamp()) {
          setSkillPointTimeStamp(other.getSkillPointTimeStamp());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSkillPoint()) {
          
          return false;
        }
        if (!hasSkillPointTimeStamp()) {
          
          return false;
        }
        for (int i = 0; i < getInstanceStateCount(); i++) {
          if (!getInstanceState(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.Statistics.HSStatisticsInfoSync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.Statistics.HSStatisticsInfoSync) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .InstanceState instanceState = 1;
      private java.util.List<com.hawk.game.protocol.Statistics.InstanceState> instanceState_ =
        java.util.Collections.emptyList();
      private void ensureInstanceStateIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          instanceState_ = new java.util.ArrayList<com.hawk.game.protocol.Statistics.InstanceState>(instanceState_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.Statistics.InstanceState, com.hawk.game.protocol.Statistics.InstanceState.Builder, com.hawk.game.protocol.Statistics.InstanceStateOrBuilder> instanceStateBuilder_;

      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public java.util.List<com.hawk.game.protocol.Statistics.InstanceState> getInstanceStateList() {
        if (instanceStateBuilder_ == null) {
          return java.util.Collections.unmodifiableList(instanceState_);
        } else {
          return instanceStateBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public int getInstanceStateCount() {
        if (instanceStateBuilder_ == null) {
          return instanceState_.size();
        } else {
          return instanceStateBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public com.hawk.game.protocol.Statistics.InstanceState getInstanceState(int index) {
        if (instanceStateBuilder_ == null) {
          return instanceState_.get(index);
        } else {
          return instanceStateBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public Builder setInstanceState(
          int index, com.hawk.game.protocol.Statistics.InstanceState value) {
        if (instanceStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstanceStateIsMutable();
          instanceState_.set(index, value);
          onChanged();
        } else {
          instanceStateBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public Builder setInstanceState(
          int index, com.hawk.game.protocol.Statistics.InstanceState.Builder builderForValue) {
        if (instanceStateBuilder_ == null) {
          ensureInstanceStateIsMutable();
          instanceState_.set(index, builderForValue.build());
          onChanged();
        } else {
          instanceStateBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public Builder addInstanceState(com.hawk.game.protocol.Statistics.InstanceState value) {
        if (instanceStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstanceStateIsMutable();
          instanceState_.add(value);
          onChanged();
        } else {
          instanceStateBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public Builder addInstanceState(
          int index, com.hawk.game.protocol.Statistics.InstanceState value) {
        if (instanceStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstanceStateIsMutable();
          instanceState_.add(index, value);
          onChanged();
        } else {
          instanceStateBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public Builder addInstanceState(
          com.hawk.game.protocol.Statistics.InstanceState.Builder builderForValue) {
        if (instanceStateBuilder_ == null) {
          ensureInstanceStateIsMutable();
          instanceState_.add(builderForValue.build());
          onChanged();
        } else {
          instanceStateBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public Builder addInstanceState(
          int index, com.hawk.game.protocol.Statistics.InstanceState.Builder builderForValue) {
        if (instanceStateBuilder_ == null) {
          ensureInstanceStateIsMutable();
          instanceState_.add(index, builderForValue.build());
          onChanged();
        } else {
          instanceStateBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public Builder addAllInstanceState(
          java.lang.Iterable<? extends com.hawk.game.protocol.Statistics.InstanceState> values) {
        if (instanceStateBuilder_ == null) {
          ensureInstanceStateIsMutable();
          super.addAll(values, instanceState_);
          onChanged();
        } else {
          instanceStateBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public Builder clearInstanceState() {
        if (instanceStateBuilder_ == null) {
          instanceState_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          instanceStateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public Builder removeInstanceState(int index) {
        if (instanceStateBuilder_ == null) {
          ensureInstanceStateIsMutable();
          instanceState_.remove(index);
          onChanged();
        } else {
          instanceStateBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public com.hawk.game.protocol.Statistics.InstanceState.Builder getInstanceStateBuilder(
          int index) {
        return getInstanceStateFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public com.hawk.game.protocol.Statistics.InstanceStateOrBuilder getInstanceStateOrBuilder(
          int index) {
        if (instanceStateBuilder_ == null) {
          return instanceState_.get(index);  } else {
          return instanceStateBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public java.util.List<? extends com.hawk.game.protocol.Statistics.InstanceStateOrBuilder> 
           getInstanceStateOrBuilderList() {
        if (instanceStateBuilder_ != null) {
          return instanceStateBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(instanceState_);
        }
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public com.hawk.game.protocol.Statistics.InstanceState.Builder addInstanceStateBuilder() {
        return getInstanceStateFieldBuilder().addBuilder(
            com.hawk.game.protocol.Statistics.InstanceState.getDefaultInstance());
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public com.hawk.game.protocol.Statistics.InstanceState.Builder addInstanceStateBuilder(
          int index) {
        return getInstanceStateFieldBuilder().addBuilder(
            index, com.hawk.game.protocol.Statistics.InstanceState.getDefaultInstance());
      }
      /**
       * <code>repeated .InstanceState instanceState = 1;</code>
       *
       * <pre>
       * 副本状态
       * </pre>
       */
      public java.util.List<com.hawk.game.protocol.Statistics.InstanceState.Builder> 
           getInstanceStateBuilderList() {
        return getInstanceStateFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.Statistics.InstanceState, com.hawk.game.protocol.Statistics.InstanceState.Builder, com.hawk.game.protocol.Statistics.InstanceStateOrBuilder> 
          getInstanceStateFieldBuilder() {
        if (instanceStateBuilder_ == null) {
          instanceStateBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hawk.game.protocol.Statistics.InstanceState, com.hawk.game.protocol.Statistics.InstanceState.Builder, com.hawk.game.protocol.Statistics.InstanceStateOrBuilder>(
                  instanceState_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          instanceState_ = null;
        }
        return instanceStateBuilder_;
      }

      // repeated string monsterCollect = 2;
      private com.google.protobuf.LazyStringList monsterCollect_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMonsterCollectIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          monsterCollect_ = new com.google.protobuf.LazyStringArrayList(monsterCollect_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string monsterCollect = 2;</code>
       *
       * <pre>
       * 宠物图鉴
       * </pre>
       */
      public java.util.List<java.lang.String>
          getMonsterCollectList() {
        return java.util.Collections.unmodifiableList(monsterCollect_);
      }
      /**
       * <code>repeated string monsterCollect = 2;</code>
       *
       * <pre>
       * 宠物图鉴
       * </pre>
       */
      public int getMonsterCollectCount() {
        return monsterCollect_.size();
      }
      /**
       * <code>repeated string monsterCollect = 2;</code>
       *
       * <pre>
       * 宠物图鉴
       * </pre>
       */
      public java.lang.String getMonsterCollect(int index) {
        return monsterCollect_.get(index);
      }
      /**
       * <code>repeated string monsterCollect = 2;</code>
       *
       * <pre>
       * 宠物图鉴
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMonsterCollectBytes(int index) {
        return monsterCollect_.getByteString(index);
      }
      /**
       * <code>repeated string monsterCollect = 2;</code>
       *
       * <pre>
       * 宠物图鉴
       * </pre>
       */
      public Builder setMonsterCollect(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMonsterCollectIsMutable();
        monsterCollect_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string monsterCollect = 2;</code>
       *
       * <pre>
       * 宠物图鉴
       * </pre>
       */
      public Builder addMonsterCollect(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMonsterCollectIsMutable();
        monsterCollect_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string monsterCollect = 2;</code>
       *
       * <pre>
       * 宠物图鉴
       * </pre>
       */
      public Builder addAllMonsterCollect(
          java.lang.Iterable<java.lang.String> values) {
        ensureMonsterCollectIsMutable();
        super.addAll(values, monsterCollect_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string monsterCollect = 2;</code>
       *
       * <pre>
       * 宠物图鉴
       * </pre>
       */
      public Builder clearMonsterCollect() {
        monsterCollect_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string monsterCollect = 2;</code>
       *
       * <pre>
       * 宠物图鉴
       * </pre>
       */
      public Builder addMonsterCollectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMonsterCollectIsMutable();
        monsterCollect_.add(value);
        onChanged();
        return this;
      }

      // required int32 skillPoint = 3;
      private int skillPoint_ ;
      /**
       * <code>required int32 skillPoint = 3;</code>
       *
       * <pre>
       * 当前技能点
       * </pre>
       */
      public boolean hasSkillPoint() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 skillPoint = 3;</code>
       *
       * <pre>
       * 当前技能点
       * </pre>
       */
      public int getSkillPoint() {
        return skillPoint_;
      }
      /**
       * <code>required int32 skillPoint = 3;</code>
       *
       * <pre>
       * 当前技能点
       * </pre>
       */
      public Builder setSkillPoint(int value) {
        bitField0_ |= 0x00000004;
        skillPoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 skillPoint = 3;</code>
       *
       * <pre>
       * 当前技能点
       * </pre>
       */
      public Builder clearSkillPoint() {
        bitField0_ = (bitField0_ & ~0x00000004);
        skillPoint_ = 0;
        onChanged();
        return this;
      }

      // required int32 skillPointTimeStamp = 4;
      private int skillPointTimeStamp_ ;
      /**
       * <code>required int32 skillPointTimeStamp = 4;</code>
       *
       * <pre>
       * 下个技能点开始计时时间戳
       * </pre>
       */
      public boolean hasSkillPointTimeStamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 skillPointTimeStamp = 4;</code>
       *
       * <pre>
       * 下个技能点开始计时时间戳
       * </pre>
       */
      public int getSkillPointTimeStamp() {
        return skillPointTimeStamp_;
      }
      /**
       * <code>required int32 skillPointTimeStamp = 4;</code>
       *
       * <pre>
       * 下个技能点开始计时时间戳
       * </pre>
       */
      public Builder setSkillPointTimeStamp(int value) {
        bitField0_ |= 0x00000008;
        skillPointTimeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 skillPointTimeStamp = 4;</code>
       *
       * <pre>
       * 下个技能点开始计时时间戳
       * </pre>
       */
      public Builder clearSkillPointTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        skillPointTimeStamp_ = 0;
        onChanged();
        return this;
      }

      // optional int32 timeStamp = 5;
      private int timeStamp_ ;
      /**
       * <code>optional int32 timeStamp = 5;</code>
       *
       * <pre>
       * 服务器时间戳
       * </pre>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 timeStamp = 5;</code>
       *
       * <pre>
       * 服务器时间戳
       * </pre>
       */
      public int getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>optional int32 timeStamp = 5;</code>
       *
       * <pre>
       * 服务器时间戳
       * </pre>
       */
      public Builder setTimeStamp(int value) {
        bitField0_ |= 0x00000010;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 timeStamp = 5;</code>
       *
       * <pre>
       * 服务器时间戳
       * </pre>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timeStamp_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HSStatisticsInfoSync)
    }

    static {
      defaultInstance = new HSStatisticsInfoSync(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HSStatisticsInfoSync)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_InstanceState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InstanceState_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HSStatisticsInfoSync_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HSStatisticsInfoSync_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Protocol/Statistics.proto\"E\n\rInstanceS" +
      "tate\022\022\n\ninstanceId\030\001 \002(\t\022\014\n\004star\030\002 \002(\005\022\022" +
      "\n\ncountDaily\030\003 \001(\005\"\231\001\n\024HSStatisticsInfoS" +
      "ync\022%\n\rinstanceState\030\001 \003(\0132\016.InstanceSta" +
      "te\022\026\n\016monsterCollect\030\002 \003(\t\022\022\n\nskillPoint" +
      "\030\003 \002(\005\022\033\n\023skillPointTimeStamp\030\004 \002(\005\022\021\n\tt" +
      "imeStamp\030\005 \001(\005B\030\n\026com.hawk.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_InstanceState_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_InstanceState_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_InstanceState_descriptor,
              new java.lang.String[] { "InstanceId", "Star", "CountDaily", });
          internal_static_HSStatisticsInfoSync_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HSStatisticsInfoSync_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HSStatisticsInfoSync_descriptor,
              new java.lang.String[] { "InstanceState", "MonsterCollect", "SkillPoint", "SkillPointTimeStamp", "TimeStamp", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
