-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('Player_pb')


HSPLAYERKICKOUT = protobuf.Descriptor();
local HSPLAYERKICKOUT_REASON_FIELD = protobuf.FieldDescriptor();

HSPLAYERKICKOUT_REASON_FIELD.name = "reason"
HSPLAYERKICKOUT_REASON_FIELD.full_name = ".HSPlayerKickout.reason"
HSPLAYERKICKOUT_REASON_FIELD.number = 1
HSPLAYERKICKOUT_REASON_FIELD.index = 0
HSPLAYERKICKOUT_REASON_FIELD.label = 2
HSPLAYERKICKOUT_REASON_FIELD.has_default_value = false
HSPLAYERKICKOUT_REASON_FIELD.default_value = 0
HSPLAYERKICKOUT_REASON_FIELD.type = 5
HSPLAYERKICKOUT_REASON_FIELD.cpp_type = 1

HSPLAYERKICKOUT.name = "HSPlayerKickout"
HSPLAYERKICKOUT.full_name = ".HSPlayerKickout"
HSPLAYERKICKOUT.nested_types = {}
HSPLAYERKICKOUT.enum_types = {}
HSPLAYERKICKOUT.fields = {HSPLAYERKICKOUT_REASON_FIELD}
HSPLAYERKICKOUT.is_extendable = false
HSPLAYERKICKOUT.extensions = {}

HSPlayerKickout = protobuf.Message(HSPLAYERKICKOUT)

