-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('Skill_pb')


HSSKILL = protobuf.Descriptor();
local HSSKILL_SKILLID_FIELD = protobuf.FieldDescriptor();
local HSSKILL_LEVEL_FIELD = protobuf.FieldDescriptor();

HSSKILL_SKILLID_FIELD.name = "skillId"
HSSKILL_SKILLID_FIELD.full_name = ".HSSkill.skillId"
HSSKILL_SKILLID_FIELD.number = 1
HSSKILL_SKILLID_FIELD.index = 0
HSSKILL_SKILLID_FIELD.label = 2
HSSKILL_SKILLID_FIELD.has_default_value = false
HSSKILL_SKILLID_FIELD.default_value = 0
HSSKILL_SKILLID_FIELD.type = 5
HSSKILL_SKILLID_FIELD.cpp_type = 1

HSSKILL_LEVEL_FIELD.name = "level"
HSSKILL_LEVEL_FIELD.full_name = ".HSSkill.level"
HSSKILL_LEVEL_FIELD.number = 2
HSSKILL_LEVEL_FIELD.index = 1
HSSKILL_LEVEL_FIELD.label = 2
HSSKILL_LEVEL_FIELD.has_default_value = false
HSSKILL_LEVEL_FIELD.default_value = 0
HSSKILL_LEVEL_FIELD.type = 5
HSSKILL_LEVEL_FIELD.cpp_type = 1

HSSKILL.name = "HSSkill"
HSSKILL.full_name = ".HSSkill"
HSSKILL.nested_types = {}
HSSKILL.enum_types = {}
HSSKILL.fields = {HSSKILL_SKILLID_FIELD, HSSKILL_LEVEL_FIELD}
HSSKILL.is_extendable = false
HSSKILL.extensions = {}

HSSkill = protobuf.Message(HSSKILL)

