SPELL_CAST_OK = 0
SPELL_CAST_NO_MAMA = 1
SPELL_CAST_TARGET_DEAD = 2
SPELL_CAST_CASTER_DEAD = 3
SPELL_CAST_TARGET_IMMUNE = 4

SPELL_STATE_PREPARE = 0
SPELL_STATE_FINISH = 1

TARGET_TARGET = 0
TARGET_CASTER = 1

HIT_SUCCESS = 0
HIT_MISS = 1
HIT_IMMUNE = 2

HIT_RATE_MIN = 0.6
CRITICAL_DMG_RATIO = 1.5
PROPERTY_DMG_ADDITION = 1.25
PROPERTY_DMG_MINUS = 0.75

MAX_ROUND = 99

BUFF_REMOVE_EXPIRE = 0
BUFF_REMOVE_DISPEL = 1
BUFF_REMOVE_TARGET_DEAD = 2
BUFF_REMOVE_CASTER_DEAD = 3
BUFF_REMOVE_SHIELD_EMPTY = 4

DATA_VITAL = 0
DATA_BUFF = 1
DATA_SPELL = 2