//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Protocol/Reward.proto
// Note: requires additional types generated from: Protocol/Consume.proto
// Note: requires additional types generated from: Protocol/Attribute.proto
// Note: requires additional types generated from: Protocol/Player.proto
// Note: requires additional types generated from: Protocol/Monster.proto
namespace PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RewardItem")]
  public partial class RewardItem : global::ProtoBuf.IExtensible
  {
    public RewardItem() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _itemId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private int _stage = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"stage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stage
    {
      get { return _stage; }
      set { _stage = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private readonly global::System.Collections.Generic.List<Attr> _attrDatas = new global::System.Collections.Generic.List<Attr>();
    [global::ProtoBuf.ProtoMember(7, Name=@"attrDatas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Attr> attrDatas
    {
      get { return _attrDatas; }
    }
  
    private HSMonster _monster = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"monster", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public HSMonster monster
    {
      get { return _monster; }
      set { _monster = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HSRewardInfo")]
  public partial class HSRewardInfo : global::ProtoBuf.IExtensible
  {
    public HSRewardInfo() {}
    
    private SynPlayerAttr _playerAttr = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerAttr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SynPlayerAttr playerAttr
    {
      get { return _playerAttr; }
      set { _playerAttr = value; }
    }
    private readonly global::System.Collections.Generic.List<SynMonsterAttr> _monstersAttr = new global::System.Collections.Generic.List<SynMonsterAttr>();
    [global::ProtoBuf.ProtoMember(2, Name=@"monstersAttr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SynMonsterAttr> monstersAttr
    {
      get { return _monstersAttr; }
    }
  
    private readonly global::System.Collections.Generic.List<RewardItem> _RewardItems = new global::System.Collections.Generic.List<RewardItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"RewardItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RewardItem> RewardItems
    {
      get { return _RewardItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}